// Default car mappings from the UI
export const DEFAULT_CAR_MAPPINGS = {
  "Acura NSX GT3 EVO 22": "acuransxevo22gt3",
  "Audi R8 LMS GT3 EVO II": "audir8lmsevo2gt3",
  "BMW M4 GT3": "bmwm4gt3",
  "Chevrolet Corvette Z06 GT3.R": "chevyvettez06rgt3",
  "Ferrari 296 GT3": "ferrari296gt3",
  "Ford Mustang GT3": "fordmustanggt3",
  "Lamborghini Huracán GT3 EVO": "lamborghinievogt3",
  "McLaren 720S GT3 EVO": "mclaren720sgt3",
  "Mercedes-AMG GT3 2020": "mercedesamgevogt3",
  "Porsche 911 GT3 R (992)": "porsche992rgt3",
  "Aston Martin GT3": "amvantageevogt3",
  "Super Formula Lights  Open Wheel": "superformulalights324",
  "IR18 IndyCar  Open Wheel": "dallarair18",
  "SF23": "superformulasf23 honda",
  "Porsche 911 RSR GTE": "porsche991rsr",
  "Chevrolet Corvette C8.R GTE": "c8rvettegte",
  "BMW M8 GTE": "bmwm8gte",
  "Ligier JS P320 LMP3": "ligierjsp320",
  "Porsche 963 GTP": "porsche963gtp",
  "Cadillac V-Series R GTP": "cadillacvseriesrgtp",
  "Acura ARX-06 GTP": "acuraarx06gtp",
  "Ferrari 499P GTP": "ferrari499p",
  "Porsche 718 Cayman GT4 Clubsport MR": "porsche718gt4",
  "McLaren 570S GT4": "mclaren570sgt4",
  "Ford Mustang GT4": "fordmustanggt4",
  "Aston Martin Vantage GT4": "amvantagegt4",
  "Mercedes GT4": "mercedesamggt4",
  "BMW M4 GT4": "bmwm4gt4",
  "Dallara P217 (LMP2)": "dallarap217",
  "Honda Civic Type R TCR": "hondacivictyper",
  "Hyundai Elantra N TCR": "hyundaielantracn7",
  "Global Mazda MX-5 Cup": "mx5 cup",
  "BMW M2 CS": "bmwm2csr",
  "Porsche Cup 992": "porsche9922cup",
  "BMW M Hybrid V8 GTP": "bmwlmdh",
};

// Default track mappings (currently empty in UI)
export const DEFAULT_TRACK_MAPPINGS = {};
